name: Wes Films
favicon: null
layout_spectrum: 0.41769
typography_spectrum: 0.72034
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#df5e00'
    - '#066374'
    - '#42d3f2'
    - '#1b1b11'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
