name: Wes Films
favicon: null
layout_spectrum: 0.50172
typography_spectrum: 0.57785
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#df5e00'
    - '#066374'
    - '#42d3f2'
    - '#1b1b11'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
